# Generated by Django 3.2.5 on 2021-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0002_auto_20210708_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
