# Generated by Django 3.2.5 on 2021-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0003_alter_new_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='src',
            field=models.TextField(default=2, max_length=2000),
            preserve_default=False,
        ),
    ]
