# Generated by Django 3.2.5 on 2021-07-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0004_new_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='src',
            new_name='source_vid',
        ),
    ]
