# Generated by Django 3.2.5 on 2021-07-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
