# Generated by Django 3.2.5 on 2021-07-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0009_alter_rating_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
