# Generated by Django 3.2.5 on 2021-07-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saral', '0012_alter_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='user',
        ),
    ]
